---
title: "11 YSU Scraping"
lightbox: true
format: 
  html:
    code-fold: false
number-offset: 1
---

TODO

<a href="https://colab.research.google.com/github/HaykTarkhanyan/python_math_ml_course/blob/main/python_libs/11_ysu_scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> Song reference - ToDo



#### 📺 Տեսանյութեր
#### 🏡 Տնային

# 🛠️ Գործնական

կոդը - python_libs\scraping

# TODO

[] Add logging
[] Add tests

In [1]:
# bs4
# Beautiful Soup 4

import requests
from bs4 import BeautifulSoup

URL = "https://www.ysu.am/faculty/516/staff"

response = requests.get(URL)
soup = BeautifulSoup(response.content, "html.parser")

print(soup.prettify())

<!DOCTYPE html>
<html dir="ltr" lang="hy" prefix="og: https://ogp.me/ns#">
 <head>
  <meta charset="utf-8"/>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-44601360-1">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments)};gtag("js", new Date());gtag("set", "developer_id.dMDhkMT", true);gtag("config", "UA-44601360-1", {"groups":"default","anonymize_ip":true,"page_placeholder":"PLACEHOLDER_page_path"});
  </script>
  <link href="https://www.ysu.am/faculty/516/staff" rel="canonical"/>
  <meta content="width" name="MobileOptimized"/>
  <meta content="true" name="HandheldFriendly"/>
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
  <style>
   .item-with-image-1::before { background-image: url('/sites/default/files/styles/tablet_full_width/public/banners/%D5%8D%D4%B9%D4%B5%D5%84%20%D5%A2%D5%A1%D5%B6%D5%A5%D6%80.png?itok=Qc9AWlkJ')}  .item-with-image-2::before { background-image: url('/sites/default/files/styles/tablet_full_width/public/banners/Idjevan.png?itok=f-qXiLBF')}  .item-with-image-3::before { background-image: url('/sites/default/files/styles/tablet_full_width/public/banners/Laboratory.png?itok=u893nyOu')}
  </style>
  <meta content="ie=edge" http-equiv="x-ua-compatible"/>
  <link href="/themes/custom/ysu_main/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
  <script>
   window.a2a_config=window.a2a_config||{};a2a_config.callbacks=[];a2a_config.overlays=[];a2a_config.templates={};
  </script>
  <title>
   Աշխատակիցներ | YSU
  </title>
  <link href="/themes/custom/ysu_main/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
  <link href="/themes/custom/ysu_main/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link href="/themes/custom/ysu_main/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  <link href="/themes/custom/ysu_main/favicon/site.webmanifest" rel="manifest"/>
  <link color="#5bbad5" href="/themes/custom/ysu_main/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
  <meta content="#da532c" name="msapplication-TileColor"/>
  <meta content="#ffffff" name="theme-color"/>
  <meta content="qqVoymLkk6PL4DSmrFnXPDnYm6PKxLkJu80Rwnlfh88" name="google-site-verification">
   <link href="/sites/default/files/css/css_WQxHWeUtd69pnqOaopZBJSZOg0_mS-yZ0VZ2FtYqDSo.css?delta=0&amp;language=hy&amp;theme=ysu_main&amp;include=eJxliksKQyEMAC_k50gSNc8KJnkkscXbF0pX7WYYmIHeXYBPhq-kS4U9VBE3V7hLBdUpuSpCb7qp_jdCMxhoZc3x8NBEMTehWxjZLf3-MRLyDnbMkXIFw_Cc-LL8YSLpe2E4tgvB5DyWVFjR_KzJ4w1tLEX0" media="all" rel="stylesheet">
    <link href="/sites/default/files/css/css_tjzqM6geZhwCn-ddpZS52jNO98MEGTmlmdZ9F5TcCmg.css?delta=1&amp;language=hy&amp;theme=ysu_main&amp;include=eJxliksKQyEMAC_k50gSNc8KJnkkscXbF0pX7WYYmIHeXYBPhq-kS4U9VBE3V7hLBdUpuSpCb7qp_jdCMxhoZc3x8NBEMTehWxjZLf3-MRLyDnbMkXIFw_Cc-LL8YSLpe2E4tgvB5DyWVFjR_KzJ4w1tLEX0" media="all" rel="stylesheet">
     <link href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" media="all" rel="stylesheet">
      <link href="//fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" media="all" rel="stylesheet">
      </link>
     </link>
    </link>
   </link>
  </meta>
 </head>
 <body class="layout-one-sidebar layout-sidebar-menu has-featured-top page-view-staff path-group" style="">
  <a class="visually-hidden focusable skip-link" href="#main-content">
   Skip to main content
  </a>
  <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
   <div id="page-wrapper">
    <div class="page_not_header_footer" id="page">
     <header aria-label="Site header" class="header" id="header" role="banner">
      <nav class="navbar lang-mobile-size bg-primary navbar-expand-lg px-0 py-3 py-lg-5 text-uppercase" id="navbar-top">
       <div class="mx-xxl-7 w-100">
        <div class="container-fluid px-3 px-md-4 px-xl-6 px-xxl-5 justify-content-lg-start align-items-end">
         <div class="d-flex justify-content-between align-items-center justify-content-lg-start align-items-lg-end">
          <a class="navbar-brand me-4 me-xl-6" href="//www.ysu.am/" rel="home" title="Գլխավոր">
           <img alt="Գլխավոր" class="img-fluid d-inline-block align-top" src="/themes/custom/ysu_main/images/logo-armenian.svg"/>
          </a>
          <div class="d-flex d-lg-none align-items-end icons">
           <div class="icon">
            <a class="envelope" href="https://mail.google.com/">
             <img alt="envelope" loading="lazy" src="/themes/custom/ysu_main/images/icons/menu-icons/envelope-mobile.svg"/>
            </a>
           </div>
           <div class="dropdown search-dropdown">
            <button aria-expanded="false" class="navbar-icon lupa" data-bs-toggle="dropdown" id="main_navigation_search" type="button">
             <img alt="lupa" loading="lazy" src="/themes/custom/ysu_main/images/icons/menu-icons/lupa-mobile.svg"/>
            </button>
            <div aria-labelledby="main_navigation_search" class="dropdown-menu start-0 end-0 py-5 border-0 mt-0 rounded-0">
             <div class="container-fluid">
              <div class="row">
               <div class="col-12 col-md-8 offset-md-2">
                <div class="gcse-searchbox-only" data-resultsurl="https://www.ysu.am//explore">
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
           <div class="dropdown language-dropdown">
            <button aria-expanded="false" class="navbar-icon text-white globus" data-bs-toggle="dropdown" id="top_navbar_lang_dropdown" type="button">
             <i class="bi bi-globe" style="">
             </i>
            </button>
            <div aria-labelledby="top_navbar_lang_dropdown" class="dropdown-menu language-dropdown-menu-center top-navbar-lang-dropdown m-0 p-0" style="">
             <nav class="language-switcher-language-url nav links-inline">
              <span aria-current="page" class="hy nav-link is-active" data-drupal-link-system-path="group/516/staff" hreflang="hy">
               <a aria-current="page" class="language-link is-active" data-drupal-link-system-path="group/516/staff" href="/faculty/516/staff" hreflang="hy">
                Հայերեն
               </a>
              </span>
              <span class="ru nav-link" data-drupal-link-system-path="group/516/staff" hreflang="ru">
               <a class="language-link" data-drupal-link-system-path="group/516/staff" href="/ru/faculty/516/staff" hreflang="ru">
                Русский
               </a>
              </span>
              <span class="en nav-link" data-drupal-link-system-path="group/516/staff" hreflang="en">
               <a class="language-link" data-drupal-link-system-path="group/516/staff" href="/en/faculty/516/staff" hreflang="en">
                English
               </a>
              </span>
             </nav>
            </div>
           </div>
           <button aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler main-navbar-toggler collapsed navbar-icon d-flex justify-content-between flex-column" type="button">
            <span class="navbar-toggler-icon d-block line-1">
            </span>
            <span class="navbar-toggler-icon d-block line-2">
            </span>
            <span class="navbar-toggler-icon d-block line-3">
            </span>
           </button>
          </div>
          <div class="d-none d-lg-flex align-items-end">
           <nav aria-labelledby="block-mainnavigationarm-menu" class="block block-menu navigation menu--main-navigation-arm" id="block-mainnavigationarm" role="navigation">
            <h2 class="visually-hidden" id="block-mainnavigationarm-menu">
             Main Navigation (Arm)
            </h2>
            <ul class="clearfix nav navbar-nav">
             <li class="nav-item menu-item--expanded dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="text-decoration-none nav-link dropdown-toggle nav-link--admission" data-bs-toggle="" data-drupal-link-system-path="node/2" href="/admission">
               Ընդունելություն
              </a>
              <button aria-expanded="false" class="dropdown-toggle arrow-button d-inline-block d-lg-none" data-bs-toggle="dropdown" type="button">
              </button>
              <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--undergraduate-admission" data-drupal-link-system-path="group/22" href="/undergraduate-admission">
                 Բակալավրիատ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--masters-degree-admission" data-drupal-link-system-path="group/23" href="/masters-degree-admission">
                 Մագիստրատուրա
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--phd-studies" data-drupal-link-system-path="group/768" href="/phd-studies">
                 Ասպիրանտուրա
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--foreign-students" data-drupal-link-system-path="group/30" href="/foreign-students">
                 Օտարերկրյա ուսանողներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--preparatory-courses" data-drupal-link-system-path="group/29" href="/preparatory-courses">
                 Նախապատրաստական դասընթացներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--work-carried-out-with-applicants" data-drupal-link-system-path="group/25" href="/work-carried-out-with-applicants">
                 Դիմորդների հետ տարվող աշխատանքներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--stem-8287" data-drupal-link-system-path="node/8287" href="/STEM/8287">
                 ԵՊՀ ՍԹԵՄ ավագ դպրոց
                </a>
               </li>
              </ul>
             </li>
             <li class="nav-item menu-item--expanded dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="text-decoration-none nav-link dropdown-toggle nav-link--education" data-bs-toggle="" data-drupal-link-system-path="node/204" href="/education">
               Կրթություն
              </a>
              <button aria-expanded="false" class="dropdown-toggle arrow-button d-inline-block d-lg-none" data-bs-toggle="dropdown" type="button">
              </button>
              <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--sitesection-46" data-drupal-link-system-path="group/46" href="/sitesection-46">
                 Առաջինկուրսեցու ուղեցույց
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--educational-programs" data-drupal-link-system-path="educational-programs" href="/educational-programs">
                 Կրթական ծրագրեր
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link-__05" data-drupal-link-system-path="node/205" href="/205">
                 Մանկավարժի որակավորման շնորհում
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--academic-writing-centre" data-drupal-link-system-path="group/515" href="/Academic-Writing-Centre">
                 Ակադեմիական գրագրության կենտրոն
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--sitesection-514" data-drupal-link-system-path="group/514" href="/sitesection-514">
                 Շարունակական կրթություն
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link-__08" href="/408">
                 Ակադեմիական օրացույց
                </a>
               </li>
              </ul>
             </li>
             <li class="nav-item menu-item--expanded dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="text-decoration-none nav-link dropdown-toggle nav-link--science" data-bs-toggle="" data-drupal-link-system-path="node/170" href="/science">
               Գիտություն
              </a>
              <button aria-expanded="false" class="dropdown-toggle arrow-button d-inline-block d-lg-none" data-bs-toggle="dropdown" type="button">
              </button>
              <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--science-open-science" data-drupal-link-system-path="node/241" href="/science/open-science">
                 Բաց գիտություն
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--conferences" data-drupal-link-system-path="conferences" href="/conferences">
                 Գիտաժողովներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--library" data-drupal-link-system-path="group/494" href="/library">
                 Գրադարան
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--grants" data-drupal-link-system-path="grants" href="/grants">
                 Դրամաշնորհներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--publishing-house" data-drupal-link-system-path="group/521" href="/publishing-house">
                 Հրատարակչություն
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--councils" data-drupal-link-system-path="group/517" href="/councils">
                 Մասնագիտական խորհուրդներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--hrs4r" data-drupal-link-system-path="group/798" href="/HRS4R">
                 ՄՌԿ ռազմավարություն հետազոտողների համար
                </a>
               </li>
              </ul>
             </li>
             <li class="nav-item menu-item--expanded dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="text-decoration-none nav-link dropdown-toggle nav-link--news-and-events" data-bs-toggle="" data-drupal-link-system-path="news-and-events" href="/news-and-events">
               Նորություններ
              </a>
              <button aria-expanded="false" class="dropdown-toggle arrow-button d-inline-block d-lg-none" data-bs-toggle="dropdown" type="button">
              </button>
              <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--events" data-drupal-link-system-path="events" href="/events">
                 Իրադարձություններ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--activities" data-drupal-link-system-path="activities" href="/activities">
                 Միջոցառումներ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--news" data-drupal-link-system-path="news" href="/news">
                 Լուրեր
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link-__4897" data-drupal-link-system-path="node/74897" href="/74897">
                 Տեղեկագիր
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--announcement" data-drupal-link-system-path="announcement" href="/announcement">
                 Հայտարարություններ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--photo-galleries" data-drupal-link-system-path="photo-galleries" href="/photo-galleries">
                 Պատկերասրահ
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--video-galleries" data-drupal-link-system-path="video-galleries" href="/video-galleries">
                 Տեսադարան
                </a>
               </li>
              </ul>
             </li>
            </ul>
           </nav>
          </div>
         </div>
        </div>
       </div>
      </nav>
      <nav class="navbar navbar-expand-lg lang-desktop-size d-none d-lg-flex" id="navbar-secondary">
       <div class="mx-xxl-7 w-100">
        <div class="container-fluid px-3 px-md-4 px-xl-6 px-xxl-5 justify-content-lg-end">
         <div class="d-flex justify-content-end">
          <section class="region region-secondary_menu">
           <nav aria-labelledby="block-secondarynavigationarm-menu" class="block block-menu navigation menu--secondary-navigation-arm" id="block-secondarynavigationarm" role="navigation">
            <h2 class="visually-hidden" id="block-secondarynavigationarm-menu">
             Secondary navigation (Arm)
            </h2>
            <ul class="clearfix nav navbar-nav">
             <li class="nav-item menu-item--expanded dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="text-decoration-none nav-link dropdown-toggle nav-link--" data-bs-toggle="dropdown" data-drupal-link-system-path="&lt;front&gt;" href="/">
               ԵՊՀ-ի մասին
              </a>
              <button aria-expanded="false" class="dropdown-toggle arrow-button d-inline-block d-lg-none" data-bs-toggle="dropdown" type="button">
              </button>
              <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--ysu-management" data-drupal-link-system-path="node/274" href="/ysu-management">
                 ԵՊՀ կառավարումը
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--ysu-symbols" data-drupal-link-system-path="node/281" href="/ysu-symbols">
                 ԵՊՀ խորհրդանիշները
                </a>
               </li>
               <li class="dropdown-item item-not-below">
                <a class="text-decoration-none nav-link--international-ysu" data-drupal-link-system-path="group/28" href="/international-ysu">
                 Միջազգային համագործակցություն
                </a>
               </li>
               <li class="dropdown-item item-not-below">

In [2]:
grid = soup.find("div", class_="view-content row")
print(grid)

<div class="view-content row">
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/199" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/2022_3.jpg?h=4eadde09&amp;itok=3tiKy5CI" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Արթուր
  Արտուշի
  Սահակյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Դեկան</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/990" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/IMG_20221114_154526_1%2B.jpg?h=74f9d745&amp;itok=QR5rwFMI" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Դավիթ
  Մելսի
  Մինասյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Գրասենյակի ղեկավար-դեկանի տեղակալ</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/221" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/P1370213_8.JPG?h=52d3fcb6&amp;itok=ZAFS5Hju" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Վարուժան
  Սերյոժայի
  Աթաբեկյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի վարիչ, պրոֆեսոր</div>
<div class="d-flex justify-content-center flex-wrap mt-3 field field--name-field-user-social-media field--type-link field--label-hidden field__items">
<div class="field__item"><a href="https://orcid.org/0000-0002-6904-2570">
<img src="/sites/default/files/social-media-icons/orcid-org-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://www.researchgate.net/profile/Varuzhan-Atabekyan?ev=hdr_xprf">
<img src="/sites/default/files/social-media-icons/www-researchgate-net-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://www.semanticscholar.org/author/V.-S.-Atabekyan/143736781?sort=pub-date">
<img src="/sites/default/files/social-media-icons/www-semanticscholar-org-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://scholar.google.com/citations?hl=ru&amp;user=Fs3-gAUAAAAJ&amp;view_op=list_works&amp;sortby=pubdate">
<img src="/sites/default/files/social-media-icons/scholar-google-com-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://www.webofscience.com/wos/woscc/summary/5b544de4-a484-49e9-b5f1-fee74ed6b083-014d580ed6/relevance/1">
<img src="/sites/default/files/social-media-icons/www-webofscience-com-32px.png"/>
</a>
</div>
</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/204" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/Karen_1.jpg?h=62565f70&amp;itok=B7t8Hs-i" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Կարեն
  Լարիկի
  Ավետիսյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի վարիչ, պրոֆեսոր</div>
<div class="d-flex justify-content-center flex-wrap mt-3 field field--name-field-user-social-media field--type-link field--label-hidden field__items">
<div class="field__item"><a href="https://www.researchgate.net/profile/Karen-Avetisyan">
<img src="/sites/default/files/social-media-icons/www-researchgate-net-32px.png"/>
</a>
</div>
<div class="field__item"><a href="http://www.ams.org/mathscinet/search/author.html?mrauthid=617336">
<img src="/sites/default/files/social-media-icons/www-ams-org-32px.png"/>
</a>
</div>
</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/65" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/unnamed_40.jpg?h=f57c33c4&amp;itok=P4E8Ofb3" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Կարինե
  Ռուբենի
  Ավետիսյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի վարիչ, դոցենտ</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/215" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/IMG_9725.jpeg?h=55541bb6&amp;itok=4GhfAjBG" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Խաչատուր
  Աղավարդի
  Խաչատրյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի վարիչ, պրոֆեսոր</div>
<div class="d-flex justify-content-center flex-wrap mt-3 field field--name-field-user-social-media field--type-link field--label-hidden field__items">
<div class="field__item"><a href="https://scholar.google.com/citations?user=egljm6UAAAAJ&amp;hl=ru">
<img src="/sites/default/files/social-media-icons/scholar-google-com-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://orcid.org/0000-0002-4835-943X">
<img src="/sites/default/files/social-media-icons/orcid-org-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://www.researchgate.net/profile/Khachatur-Khachatryan-2">
<img src="/sites/default/files/social-media-icons/www-researchgate-net-32px.png"/>
</a>
</div>
</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/222" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/Copy%20of%20Yuri%20Movsisyan%20%281%29_3.jpg?h=996bdd4a&amp;itok=1IRTFcxX" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Յուրի
  Մովսեսի
  Մովսիսյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի պատվավոր վարիչ</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/134" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/%D5%8D.%D5%8B._0.png?h=0c9e5844&amp;itok=TRAKv1Sb" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Սամվել
  Հակոբի
  Ջիլավյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի վարիչ, դոցենտ</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/129" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/vik-1_0.jpg?h=70491a58&amp;itok=NWwTnPFT" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Վիկտոր
  Կարոյի
  Օհանյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Ամբիոնի վարիչ, պրոֆեսոր</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/2447" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/WP_20180920_17_50_46_Pro%20%282%29.jpg?h=4462790c&amp;itok=k8O--3Uf" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Ռաֆիկ
  Հրաչիկի
  Արամյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Պրոֆեսոր</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/137" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img alt="" class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/default_images/person%20.png?itok=XEkFVWNM" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Վանյա
  Ռաֆայելի
  Բարսեղյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Պրոֆեսոր</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/3077" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/Vasak.jpg?h=7fc0b0bc&amp;itok=ASifENlv" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Վասակ
  Հովհաննեսի
  Թորոյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Պրոֆեսոր</div>
<div class="d-flex justify-content-center flex-wrap mt-3 field field--name-field-user-social-media field--type-link field--label-hidden field__items">
<div class="field__item"><a href="https://www.researchgate.net/profile/Vasak-Toroyan">
<img src="/sites/default/files/social-media-icons/www-researchgate-net-32px.png"/>
</a>
</div>
</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/213" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/Grigori%20Karagulyan-Picture-min_0.jpg?h=8eb2588f&amp;itok=ZA81v1Lq" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Գրիգորի
  Արտաշեսի
  Կարագուլյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Պրոֆեսոր</div>
<div class="d-flex justify-content-center flex-wrap mt-3 field field--name-field-user-social-media field--type-link field--label-hidden field__items">
<div class="field__item"><a href="https://www.scopus.com/authid/detail.uri?authorId=6505855632">
<img src="/sites/default/files/social-media-icons/www-scopus-com-32px.png"/>
</a>
</div>
<div class="field__item"><a href="https://scholar.google.com/citations?user=DW08PwwAAAAJ&amp;hl=en">
<img src="/sites/default/files/social-media-icons/scholar-google-com-32px.png"/>
</a>
</div>
</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/211" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/IMG_3084_0.JPG?h=5dc9785f&amp;itok=hAc039yP" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Տիգրան
  Ներսեսի
  Հարությունյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Պրոֆեսոր</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/128" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/nk-11.jpg?h=e68b2291&amp;itok=sN4ucEw0" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Նարինե
  Գևորգի
  Ահարոնյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Դոցենտ</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/2468" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/IMG_9761_0.jpeg?h=0745fee4&amp;itok=9xM5vQwD" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Ալեքսան
  Զավենի
  Առաքելյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Դոցենտ</div>
</div>
</div>
</div></article>
</div>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/226" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/20230515_141741_0.jpg?h=6b17bdc6&amp;itok=ECpRCAwd" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">

In [4]:
cells =  grid.find_all("div", class_="col-6 col-md-3 views-row")

print(type(cells))
print(cells[0])

<class 'bs4.element.ResultSet'>
<div class="col-6 col-md-3 views-row">
<article class="profile">
<div class="user-card-view-mode">
<div class="card h-100 border-0 text-center mb-3">
<div class="user-card-body position-relative">
<a class="field-group-link" href="/user/199" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/2022_3.jpg?h=4eadde09&amp;itok=3tiKy5CI" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Արթուր
  Արտուշի
  Սահակյան

  </div>
</div></a>
</div>
<div class="card-body-outside p-3">
<div class="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item">Դեկան</div>
</div>
</div>
</div></article>
</div>

In [ ]:
cells[0].find("a")

<a class="field-group-link" href="/user/199" hreflang="hy">
<div class="m-0 field field--name-field-user-image field--type-image field--label-hidden field__item"> <img class="m-0 image-style-medium-profile" height="850" loading="lazy" src="/sites/default/files/styles/medium_profile/public/users/2022_3.jpg?h=4eadde09&amp;itok=3tiKy5CI" width="800">
</img></div>
<div class="card-body card-body-inside fw-bold position-absolute bottom-0 text-light w-100 pb-3 pt-7">
<div class="user-full-name h5 fw-bold m-0">
      Արթուր
  Արտուշի
  Սահակյան

  </div>
</div></a>

In [13]:
print(cells[0].find("a").attrs)
cells[0].find("a")["href"]

{'href': '/user/199', 'class': ['field-group-link'], 'hreflang': 'hy'}

'/user/199'

In [20]:
name = cells[0].find("div", class_="user-full-name").text.strip()

In [ ]:
def clean_name(name):
    return name.strip().replace("\n", " ").replace("  ", " ")

clean_name(name)

'Արթուր  Արտուշի  Սահակյան'

In [22]:
position = cells[0].find("div", class_="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item").text.strip()
position

'Դեկան'

In [27]:
from tqdm import tqdm

res = []

for cell in tqdm(cells):
    url = cell.find("a")["href"]
    img = cell.find("img")["src"]
    name = clean_name(cell.find("div", class_="user-full-name").text)
    position = cell.find("div", class_="field field--name-field-user-intranet-position field--type-entity-reference field--label-hidden field__item").text.strip()
    
    res.append({
        "name": name,
        "position": position,
        "url": url,
        "img": img
    })
    
res[0]

100%|██████████| 108/108 [00:00<00:00, 3650.25it/s]

{'name': 'Արթուր  Արտուշի  Սահակյան',
 'position': 'Դեկան',
 'url': '/user/199',
 'img': '/sites/default/files/styles/medium_profile/public/users/2022_3.jpg?h=4eadde09&itok=3tiKy5CI'}

In [28]:
import pandas as pd

df = pd.DataFrame(res)
df

,name,position,url,img
0,Արթուր Արտուշի Սահակյան,Դեկան,/user/199,/sites/default/files/styles/medium_profile/pub...
1,Դավիթ Մելսի Մինասյան,Գրասենյակի ղեկավար-դեկանի տեղակալ,/user/990,/sites/default/files/styles/medium_profile/pub...
2,Վարուժան Սերյոժայի Աթաբեկյան,"Ամբիոնի վարիչ, պրոֆեսոր",/user/221,/sites/default/files/styles/medium_profile/pub...
3,Կարեն Լարիկի Ավետիսյան,"Ամբիոնի վարիչ, պրոֆեսոր",/user/204,/sites/default/files/styles/medium_profile/pub...
4,Կարինե Ռուբենի Ավետիսյան,"Ամբիոնի վարիչ, դոցենտ",/user/65,/sites/default/files/styles/medium_profile/pub...
...,...,...,...,...
103,Լուսինե Միքայելի Հակոբյան,Վարչարարության մասնագետ,/user/1339,/sites/default/files/styles/medium_profile/pub...
104,Տիգրանուհի Կարապետի Հովհաննիսյան,Վարչարարության մասնագետ,/user/3104,/sites/default/files/styles/medium_profile/pub...
105,Արաքս Հրայրի Մարգարյան,Վարչարարության մասնագետ,/user/52,/sites/default/files/styles/medium_profile/pub...
106,Լուսինե Աշոտի Ռաշոյան,Վարչարարության մասնագետ,/user/988,/sites/default/files/styles/medium_profile/pub...
107,Արմինե Հրաչիկի Օհանյան,Վարչարարության մասնագետ,/user/3080,/sites/default/files/styles/medium_profile/pub...

In [30]:
df.isna().sum()

name        0
position    0
url         0
img         0
dtype: int64

In [31]:
assert df.isna().sum().sum() == 0, "There are missing values in the DataFrame"

## Per person

'/user/221'

In [40]:
import os
from pathlib import Path

BASE_URL = "https://www.ysu.am"
SAVE_DIR = Path("scraping", "htmls_ysu")

os.makedirs(SAVE_DIR, exist_ok=True)

i = 2
name = clean_name(df.iloc[i]["name"])
url_suffix = df.iloc[i]["url"]


url = BASE_URL + url_suffix

response = requests.get(url)
response

In [41]:
print(response.text)

<!DOCTYPE html>
<html lang="hy" dir="ltr" prefix="og: https://ogp.me/ns#">
  <head>
    <meta charset="utf-8" />
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-44601360-1"></script>
<script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments)};gtag("js", new Date());gtag("set", "developer_id.dMDhkMT", true);gtag("config", "UA-44601360-1", {"groups":"default","anonymize_ip":true,"page_placeholder":"PLACEHOLDER_page_path"});</script>
<meta name="description" content="Վարուժան Սերյոժայի Աթաբեկյան" />
<link rel="canonical" href="https://www.ysu.am/user/221" />
<meta name="MobileOptimized" content="width" />
<meta name="HandheldFriendly" content="true" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<style>.item-with-image-1::before { background-image: url('/sites/default/files/styles/tablet_full_width/public/banners/%D5%8D%D4%B9%D4%B5%D5%84%20%D5%A2%D5%A1%D5%B6%D5%A5%D6%80.png?itok=Qc9AWlkJ')}  .item-with-image-2::before { background-image: url('/sites/default/files/styles/tablet_full_width/public/banners/Idjevan.png?itok=f-qXiLBF')}  .item-with-image-3::before { background-image: url('/sites/default/files/styles/tablet_full_width/public/banners/Laboratory.png?itok=u893nyOu')} </style>
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<link rel="icon" href="/themes/custom/ysu_main/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="alternate" hreflang="hy" href="https://www.ysu.am/user/221" />
<link rel="alternate" hreflang="ru" href="https://www.ysu.am/ru/user/221" />
<link rel="alternate" hreflang="en" href="https://www.ysu.am/en/user/221" />
<script>window.a2a_config=window.a2a_config||{};a2a_config.callbacks=[];a2a_config.overlays=[];a2a_config.templates={};</script>

    <title>Վարուժան Սերյոժայի Աթաբեկյան | YSU</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/themes/custom/ysu_main/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/themes/custom/ysu_main/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/themes/custom/ysu_main/favicon/favicon-16x16.png">
    <link rel="manifest" href="/themes/custom/ysu_main/favicon/site.webmanifest">
    <link rel="mask-icon" href="/themes/custom/ysu_main/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="google-site-verification" content="qqVoymLkk6PL4DSmrFnXPDnYm6PKxLkJu80Rwnlfh88" />
    <link rel="stylesheet" media="all" href="/sites/default/files/css/css_nArLFEzWLro5I0X8dtny4uLICehUdHCDxeQGrKNGUCo.css?delta=0&amp;language=hy&amp;theme=ysu_main&amp;include=eJxlj1FuxCAMRC9E4EjIBIdQGYxs0y57-ka7rSo1P5Y98zzSQM7G0FeAn8Ufwt1cQjOUiI_Bijkela5TQ8GOAuQSwXOFBIouMZuawIgJRCqHJAh5l9nS3TtY2l1tqAoFNVItp939zhndzoJh5za4Yzf1_6lta9jnG8syB5CHD3i4oyLlWITnCEh4QeZPlvq8agJFg6RugEC5ok79ff1T_OxjJqp6Yna61LC9i39W_NLwmr5xnoRu6YwNag-FOAFtaotqL9_OgYzq" />
<link rel="stylesheet" media="all" href="/sites/default/files/css/css_Y1m4eHl1r6kwPLmiPW8jFzyLKxT5Uw4Q39JPKWLES5c.css?delta=1&amp;language=hy&amp;theme=ysu_main&amp;include=eJxlj1FuxCAMRC9E4EjIBIdQGYxs0y57-ka7rSo1P5Y98zzSQM7G0FeAn8Ufwt1cQjOUiI_Bijkela5TQ8GOAuQSwXOFBIouMZuawIgJRCqHJAh5l9nS3TtY2l1tqAoFNVItp939zhndzoJh5za4Yzf1_6lta9jnG8syB5CHD3i4oyLlWITnCEh4QeZPlvq8agJFg6RugEC5ok79ff1T_OxjJqp6Yna61LC9i39W_NLwmr5xnoRu6YwNag-FOAFtaotqL9_OgYzq" />
<link rel="stylesheet" media="all" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
<link rel="stylesheet" media="all" href="//fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />


  </head>
  <body class="layout-no-sidebars has-featured-top page-user-221 path-user"
    style="">
    <a href="#main-content" class="visually-hidden focusable skip-link">
      Skip to main content
    </a>

      <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas>


<div  id="page-wrapper">
  <div id="page" class=" page_not_header_footer ">
            <header id="header" class="header" role="banner" aria-label="Site header">
                <nav  class="navbar lang-mobile-size bg-primary navbar-expand-lg px-0 py-3 py-lg-5 text-uppercase" id="navbar-top">
        <div class="mx-xxl-7 w-100">
                    <div class="container-fluid px-3 px-md-4 px-xl-6 px-xxl-5 justify-content-lg-start align-items-end">
                        <div class="d-flex justify-content-between align-items-center justify-content-lg-start align-items-lg-end">
                              <a href="//www.ysu.am/" title="Գլխավոր" rel="home" class="navbar-brand me-4 me-xl-6">
                                      <img src="/themes/custom/ysu_main/images/logo-armenian.svg" alt="Գլխավոր" class="img-fluid d-inline-block align-top" />
                                  </a>
                            <div class="d-flex d-lg-none align-items-end icons">
                <div class="icon">
                  <a class="envelope" href="https://mail.google.com/">
                    <img loading="lazy" src="/themes/custom/ysu_main/images/icons/menu-icons/envelope-mobile.svg" alt="envelope">
                  </a>
                </div>
                <div class="dropdown search-dropdown">
  <button class="navbar-icon lupa" type="button" id="main_navigation_search" data-bs-toggle="dropdown" aria-expanded="false">
    <img loading="lazy" src="/themes/custom/ysu_main/images/icons/menu-icons/lupa-mobile.svg" alt="lupa">
  </button>
  <div class="dropdown-menu start-0 end-0 py-5 border-0 mt-0 rounded-0" aria-labelledby="main_navigation_search">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-md-8 offset-md-2">
          <div class="gcse-searchbox-only" data-resultsUrl="https://www.ysu.am//explore"></div>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="dropdown language-dropdown">
  <button class="navbar-icon text-white globus" type="button" id="top_navbar_lang_dropdown" data-bs-toggle="dropdown"
          aria-expanded="false">
    <i class="bi bi-globe" style=></i>
  </button>
  <div class="dropdown-menu language-dropdown-menu-center top-navbar-lang-dropdown m-0 p-0"
       aria-labelledby="top_navbar_lang_dropdown" style="">


  <nav class="language-switcher-language-url nav links-inline"><span hreflang="hy" data-drupal-link-system-path="user/221" class="hy nav-link is-active" aria-current="page"><a href="/user/221" class="language-link is-active" hreflang="hy" data-drupal-link-system-path="user/221" aria-current="page">Հայերեն</a></span><span hreflang="ru" data-drupal-link-system-path="user/221" class="ru nav-link"><a href="/ru/user/221" class="language-link" hreflang="ru" data-drupal-link-system-path="user/221">Русский</a></span><span hreflang="en" data-drupal-link-system-path="user/221" class="en nav-link"><a href="/en/user/221" class="language-link" hreflang="en" data-drupal-link-system-path="user/221">English</a></span></nav>

  </div>
</div>
                <button class="navbar-toggler main-navbar-toggler collapsed navbar-icon d-flex justify-content-between flex-column" type="button" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon d-block line-1"></span>
                  <span class="navbar-toggler-icon d-block line-2"></span>
                  <span class="navbar-toggler-icon d-block line-3"></span>
                </button>
              </div>
              <div class="d-none d-lg-flex align-items-end">
                  <nav role="navigation" aria-labelledby="block-mainnavigationarm-menu" id="block-mainnavigationarm" class="block block-menu navigation menu--main-navigation-arm">

  <h2 class="visually-hidden" id="block-mainnavigationarm-menu">Main Navigation (Arm)</h2>




        <ul class="clearfix nav navbar-nav">

                <li class="nav-item menu-item--expanded dropdown">
                                          <a href="/admission" class="text-decoration-none nav-link dropdown-toggle nav-link--admission" data-bs-toggle="" aria-expanded="false" aria-haspopup="true" data-drupal-link-system-path="node/2">Ընդունելություն</a>
              <button class="dropdown-toggle arrow-button d-inline-block d-lg-none" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>

        <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">

                <li class="dropdown-item item-not-below">
                          <a href="/undergraduate-admission" class="text-decoration-none nav-link--undergraduate-admission" data-drupal-link-system-path="group/22">Բակալավրիատ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/masters-degree-admission" class="text-decoration-none nav-link--masters-degree-admission" data-drupal-link-system-path="group/23">Մագիստրատուրա</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/phd-studies" class="text-decoration-none nav-link--phd-studies" data-drupal-link-system-path="group/768">Ասպիրանտուրա</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/foreign-students" class="text-decoration-none nav-link--foreign-students" data-drupal-link-system-path="group/30">Օտարերկրյա ուսանողներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/preparatory-courses" class="text-decoration-none nav-link--preparatory-courses" data-drupal-link-system-path="group/29">Նախապատրաստական դասընթացներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/work-carried-out-with-applicants" class="text-decoration-none nav-link--work-carried-out-with-applicants" data-drupal-link-system-path="group/25">Դիմորդների հետ տարվող աշխատանքներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/STEM/8287" class="text-decoration-none nav-link--stem-8287" data-drupal-link-system-path="node/8287">ԵՊՀ ՍԹԵՄ ավագ դպրոց</a>
                </li>
      </ul>

                </li>
                <li class="nav-item menu-item--expanded dropdown">
                                          <a href="/education" class="text-decoration-none nav-link dropdown-toggle nav-link--education" data-bs-toggle="" aria-expanded="false" aria-haspopup="true" data-drupal-link-system-path="node/204">Կրթություն</a>
              <button class="dropdown-toggle arrow-button d-inline-block d-lg-none" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>

        <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">

                <li class="dropdown-item item-not-below">
                          <a href="/sitesection-46" class="text-decoration-none nav-link--sitesection-46" data-drupal-link-system-path="group/46">Առաջինկուրսեցու ուղեցույց</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/educational-programs" class="text-decoration-none nav-link--educational-programs" data-drupal-link-system-path="educational-programs">Կրթական ծրագրեր</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/205" class="text-decoration-none nav-link-__05" data-drupal-link-system-path="node/205">Մանկավարժի որակավորման շնորհում</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/Academic-Writing-Centre" class="text-decoration-none nav-link--academic-writing-centre" data-drupal-link-system-path="group/515">Ակադեմիական գրագրության կենտրոն</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/sitesection-514" class="text-decoration-none nav-link--sitesection-514" data-drupal-link-system-path="group/514">Շարունակական կրթություն</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/408" class="text-decoration-none nav-link-__08">Ակադեմիական օրացույց</a>
                </li>
      </ul>

                </li>
                <li class="nav-item menu-item--expanded dropdown">
                                          <a href="/science" class="text-decoration-none nav-link dropdown-toggle nav-link--science" data-bs-toggle="" aria-expanded="false" aria-haspopup="true" data-drupal-link-system-path="node/170">Գիտություն</a>
              <button class="dropdown-toggle arrow-button d-inline-block d-lg-none" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>

        <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">

                <li class="dropdown-item item-not-below">
                          <a href="/science/open-science" class="text-decoration-none nav-link--science-open-science" data-drupal-link-system-path="node/241">Բաց գիտություն</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/conferences" class="text-decoration-none nav-link--conferences" data-drupal-link-system-path="conferences">Գիտաժողովներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/library" class="text-decoration-none nav-link--library" data-drupal-link-system-path="group/494">Գրադարան</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/grants" class="text-decoration-none nav-link--grants" data-drupal-link-system-path="grants">Դրամաշնորհներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/publishing-house" class="text-decoration-none nav-link--publishing-house" data-drupal-link-system-path="group/521">Հրատարակչություն</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/councils" class="text-decoration-none nav-link--councils" data-drupal-link-system-path="group/517">Մասնագիտական խորհուրդներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/HRS4R" class="text-decoration-none nav-link--hrs4r" data-drupal-link-system-path="group/798">ՄՌԿ ռազմավարություն հետազոտողների համար</a>
                </li>
      </ul>

                </li>
                <li class="nav-item menu-item--expanded dropdown">
                                          <a href="/news-and-events" class="text-decoration-none nav-link dropdown-toggle nav-link--news-and-events" data-bs-toggle="" aria-expanded="false" aria-haspopup="true" data-drupal-link-system-path="news-and-events">Նորություններ</a>
              <button class="dropdown-toggle arrow-button d-inline-block d-lg-none" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>

        <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">

                <li class="dropdown-item item-not-below">
                          <a href="/events" class="text-decoration-none nav-link--events" data-drupal-link-system-path="events">Իրադարձություններ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/activities" class="text-decoration-none nav-link--activities" data-drupal-link-system-path="activities">Միջոցառումներ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/news" class="text-decoration-none nav-link--news" data-drupal-link-system-path="news">Լուրեր</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/74897" class="text-decoration-none nav-link-__4897" data-drupal-link-system-path="node/74897">Տեղեկագիր</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/announcement" class="text-decoration-none nav-link--announcement" data-drupal-link-system-path="announcement">Հայտարարություններ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/photo-galleries" class="text-decoration-none nav-link--photo-galleries" data-drupal-link-system-path="photo-galleries">Պատկերասրահ</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/video-galleries" class="text-decoration-none nav-link--video-galleries" data-drupal-link-system-path="video-galleries">Տեսադարան</a>
                </li>
      </ul>

                </li>
      </ul>



  </nav>


              </div>
            </div>
                      </div>
                  </div>
      </nav>
            <nav  class="navbar navbar-expand-lg lang-desktop-size d-none d-lg-flex" id="navbar-secondary">
        <div class="mx-xxl-7 w-100">
                    <div class="container-fluid px-3 px-md-4 px-xl-6 px-xxl-5 justify-content-lg-end">
                        <div class="d-flex justify-content-end">
                <section class="region region-secondary_menu">
    <nav role="navigation" aria-labelledby="block-secondarynavigationarm-menu" id="block-secondarynavigationarm" class="block block-menu navigation menu--secondary-navigation-arm">

  <h2 class="visually-hidden" id="block-secondarynavigationarm-menu">Secondary navigation (Arm)</h2>




        <ul class="clearfix nav navbar-nav">

                <li class="nav-item menu-item--expanded dropdown">
                                          <a href="/" class="text-decoration-none nav-link dropdown-toggle nav-link--" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true" data-drupal-link-system-path="&lt;front&gt;">ԵՊՀ-ի մասին</a>
              <button class="dropdown-toggle arrow-button d-inline-block d-lg-none" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>

        <ul class="dropdown-menu rounded-0 p-0 m-0 border-0">

                <li class="dropdown-item item-not-below">
                          <a href="/ysu-management" class="text-decoration-none nav-link--ysu-management" data-drupal-link-system-path="node/274">ԵՊՀ կառավարումը</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/ysu-symbols" class="text-decoration-none nav-link--ysu-symbols" data-drupal-link-system-path="node/281">ԵՊՀ խորհրդանիշները</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/international-ysu" class="text-decoration-none nav-link--international-ysu" data-drupal-link-system-path="group/28">Միջազգային համագործակցություն</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/quality-assurance" class="text-decoration-none nav-link--quality-assurance" data-drupal-link-system-path="group/27">Որակի ապահովում</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/museum" class="text-decoration-none nav-link--museum" data-drupal-link-system-path="group/522">ԵՊՀ պատմության թանգարան</a>
                </li>
                <li class="dropdown-item item-not-below">
                          <a href="/HRM" class="text-decoration-none nav-link--hrm" data-drupal-link-system-path="group/859">Աշխատանք ԵՊՀ-ում</a>
                </li>
                <li class="dropdown-item item-not-below">

In [42]:
filename = f"{SAVE_DIR}/{i}_{clean_name(name)}.html"

with open(filename, "w", encoding="utf-8") as file:
    file.write(response.text)

In [55]:
def get_html(i, row):
    print(f"Processing {i}: {row['name']}")
    if i < 10:
        i = f"0{i}"

    name = clean_name(row["name"])
    filename = Path(SAVE_DIR) / f"{i}_{name}.html"

    if filename.exists():
        print(f"File {filename} already exists. Skipping download.")
        return 

    url_suffix = row["url"]
    url = BASE_URL + url_suffix
    
        
    response = requests.get(url)
    response.raise_for_status()  # Ensure we got a successful response
    
    text = response.text
    
    with open(filename, "w", encoding="utf-8") as file:
        file.write(text)
        
    return filename

In [ ]:
%%time
for i, row in tqdm(df.iterrows(), total=len(df)):
    get_html(i, row)

## Parallel processing

In [56]:
from joblib import Parallel, delayed

In [ ]:
%%time

Parallel(n_jobs=4)( # -1 = all
    delayed(get_html)(i, row) for i, row in df.iterrows()
)

## Year of birth

In [66]:
df

,name,position,url,img
0,Արթուր Արտուշի Սահակյան,Դեկան,/user/199,/sites/default/files/styles/medium_profile/pub...
1,Դավիթ Մելսի Մինասյան,Գրասենյակի ղեկավար-դեկանի տեղակալ,/user/990,/sites/default/files/styles/medium_profile/pub...
2,Վարուժան Սերյոժայի Աթաբեկյան,"Ամբիոնի վարիչ, պրոֆեսոր",/user/221,/sites/default/files/styles/medium_profile/pub...
3,Կարեն Լարիկի Ավետիսյան,"Ամբիոնի վարիչ, պրոֆեսոր",/user/204,/sites/default/files/styles/medium_profile/pub...
4,Կարինե Ռուբենի Ավետիսյան,"Ամբիոնի վարիչ, դոցենտ",/user/65,/sites/default/files/styles/medium_profile/pub...
...,...,...,...,...
103,Լուսինե Միքայելի Հակոբյան,Վարչարարության մասնագետ,/user/1339,/sites/default/files/styles/medium_profile/pub...
104,Տիգրանուհի Կարապետի Հովհաննիսյան,Վարչարարության մասնագետ,/user/3104,/sites/default/files/styles/medium_profile/pub...
105,Արաքս Հրայրի Մարգարյան,Վարչարարության մասնագետ,/user/52,/sites/default/files/styles/medium_profile/pub...
106,Լուսինե Աշոտի Ռաշոյան,Վարչարարության մասնագետ,/user/988,/sites/default/files/styles/medium_profile/pub...
107,Արմինե Հրաչիկի Օհանյան,Վարչարարության մասնագետ,/user/3080,/sites/default/files/styles/medium_profile/pub...

In [74]:
def get_year_of_birth(soup):
    personal_info = soup.find("div", class_ = "personal-information")
    date_of_birth = personal_info.find("div", class_="fw-bold d-flex field field--name-field-user-date-of-birth field--type-datetime field--label-above")
    date_of_birth_text_list = date_of_birth.text.strip().split("\n")
    title = date_of_birth_text_list[0]
    year = date_of_birth_text_list[1]
    
    
    if title == "Ծննդյան տարեթիվ":
        year_of_birth = year
    else:
        print(f"Title mismatch: {title}. Expected 'Ծննդյան տարեթիվ'.")
        year_of_birth = "Unknown"
        
    return year_of_birth

In [78]:
for i, row in tqdm(df.iterrows(), total=len(df)):
    if i < 10:
        i_file = f"0{i}"
    else:
        i_file = i
    file_name = f"{SAVE_DIR}/{i_file}_{clean_name(row['name'])}.html"
    
    try:
        with open(file_name, "r", encoding="utf-8") as f:
            html = f.read()
    except FileNotFoundError:
        print(f"File {file_name} not found. Skipping {row['name']}.")
        continue
    
    soup = BeautifulSoup(html, "html.parser")
    try:
        year_of_birth = get_year_of_birth(soup)
    except Exception as e:
        print(f"Error processing {i} {row['name']}: {e}")
        year_of_birth = None
    
    df.loc[i, "year"] = year_of_birth

 61%|██████    | 72/118 [00:13<00:06,  6.59it/s]

Error processing 70 Նիկոլայ  Վյաչեսլավի  Կարպով: 'NoneType' object has no attribute 'find'

 92%|█████████▏| 108/118 [00:18<00:01,  5.86it/s]

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
df.fillna(0)

count      118
unique      45
top       1977
freq         7
Name: year, dtype: object

# 🏡Տնային


<a href="https://s01.flagcounter.com/more/1oO/"><img src="https://s01.flagcounter.com/count2/1oO/bg_FFFFFF/txt_000000/border_CCCCCC/columns_2/maxflags_10/viewers_0/labels_0/pageviews_1/flags_0/percent_0/" alt="Flag Counter"></a>